---
- name: Install vim
  ansible.builtin.apt:
    pkg: vim
    state: present

- name: Write vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: /etc/vim/vimrc
    owner: root
    group: root
    mode: "0644"

- name: Set vim alternatives
  community.general.alternatives:
    name: "{{ item }}"
    path: "/usr/bin/vim.basic"
  with_items: [editor, ex, rview, rvim, vi, view, vim, vimdiff]
